# Generated by Django 3.2.3 on 2024-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=234, verbose_name='Почта')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
        ),
    ]
